import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Plataforma',
      items: [{type: 'autogenerated', dirName: 'plataforma'}],
    },
    {
      type: 'category',
      label: 'Integraciones',
      items: [{type: 'autogenerated', dirName: 'integraciones'}],
    },
  ],
};

export default sidebars;
